// H17

List hiloDeviationChart = [
  // [
  //   {'play': 'S', 'deviation': 'Insurance'},
  //   {'play': 'S', 'deviation': '+3'}
  // ], // Dealer
  [
    {'heading': ''}, 
    {'heading': '2'}, 
    {'heading': '3'}, 
    {'heading': '4'}, 
    {'heading': '5'}, 
    {'heading': '6'}, 
    {'heading': '7'}, 
    {'heading': '8'}, 
    {'heading': '9'}, 
    {'heading': '10'}, 
    {'heading': 'A'},
  ], // Dealer

  [
    {'heading': '18'},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
  ],
  [
    {'heading': '17'},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'Rs', 'deviation': null},
  ],
  [
    {'heading': '16'},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'Rh', 'deviation': '+5'},
    {'play': 'H', 'deviation': '0'},
    {'play': 'Rh', 'deviation': null},
  ],
  [
    {'heading': '15'},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': '+2'},
    {'play': 'H', 'deviation': '4/0'},
    {'play': 'Rh', 'deviation': '+1'},
  ],
  [
    {'heading': '14'},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': '+3'},
    {'play': 'H', 'deviation': null},
  ],
  [
    {'heading': '13'},
    {'play': 'S', 'deviation': '-1'},
    {'play': 'S', 'deviation': '-2'},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
  ],
  [
    {'heading': '12'},
    {'play': 'H', 'deviation': '+3'},
    {'play': 'H', 'deviation': '+2'},
    {'play': 'S', 'deviation': '0'},
    {'play': 'S', 'deviation': '-2'},
    {'play': 'S', 'deviation': '-1'},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
  ],
  [
    {'heading': '11'},
    {'play': 'Dh', 'deviation': null},
    {'play': 'Dh', 'deviation': null},
    {'play': 'Dh', 'deviation': null},
    {'play': 'Dh', 'deviation': null},
    {'play': 'Dh', 'deviation': null},
    {'play': 'Dh', 'deviation': null},
    {'play': 'Dh', 'deviation': null},
    {'play': 'Dh', 'deviation': null},
    {'play': 'Dh', 'deviation': null},
    {'play': 'H', 'deviation': '+1'},
  ],
  [
    {'heading': '10'},
    {'play': 'Dh', 'deviation': null},
    {'play': 'Dh', 'deviation': null},
    {'play': 'Dh', 'deviation': null},
    {'play': 'Dh', 'deviation': null},
    {'play': 'Dh', 'deviation': null},
    {'play': 'Dh', 'deviation': null},
    {'play': 'Dh', 'deviation': null},
    {'play': 'Dh', 'deviation': null},
    {'play': 'H', 'deviation': '+4'},
    {'play': 'H', 'deviation': '+4'},
  ],
  [
    {'heading': '9'},
    {'play': 'H', 'deviation': '+1'},
    {'play': 'Dh', 'deviation': null},
    {'play': 'Dh', 'deviation': null},
    {'play': 'Dh', 'deviation': null},
    {'play': 'Dh', 'deviation': null},
    {'play': 'H', 'deviation': '+3'},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
  ],
  [
    {'heading': '8'},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
  ],
  [
    {'heading': '<7'},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
  ],
  [
    {'heading': '10,10'},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': '+5'},
    {'play': 'H', 'deviation': '+4'},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
  ],
    [
    {'heading': ''}, 
    {'heading': '2'}, 
    {'heading': '3'}, 
    {'heading': '4'}, 
    {'heading': '5'}, 
    {'heading': '6'}, 
    {'heading': '7'}, 
    {'heading': '8'}, 
    {'heading': '9'}, 
    {'heading': '10'}, 
    {'heading': 'A'},
  ], // Dealer
];



//   {'dealer': '10', 'player': '15', 'answer': '0'},

//   {'dealer': '9', 'player': '15', 'answer': '+2'},
//   {'dealer': 'A', 'player': '15', 'answer': '+1'},
// ];