// H17

List rekoDeviationChart = [
  [
    {'heading': ''}, 
    {'heading': '2'}, 
    {'heading': '3'}, 
    {'heading': '4'}, 
    {'heading': '5'}, 
    {'heading': '6'}, 
    {'heading': '7'}, 
    {'heading': '8'}, 
    {'heading': '9'}, 
    {'heading': '10'}, 
    {'heading': 'A'},
  ], // Dealer

  [
    {'heading': '18'},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
  ],
  [
    {'heading': '17'},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'Rs', 'deviation': null},
  ],
  [
    {'heading': '16'},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'Rh', 'deviation': null},
    {'play': 'H', 'deviation': '-9'},
    {'play': 'Rh', 'deviation': null},
  ],
  [
    {'heading': '15'},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': '+2'},
    {'play': 'Rh', 'deviation': null},
  ],
  [
    {'heading': '14'},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
  ],
  [
    {'heading': '13'},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
  ],
  [
    {'heading': '12'},
    {'play': 'H', 'deviation': '+2'},
    {'play': 'H', 'deviation': '+2'},
    {'play': 'S', 'deviation': '+2'},
    {'play': 'S', 'deviation': null},
    {'play': 'S', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
  ],
  [
    {'heading': '11'},
    {'play': 'Dh', 'deviation': null},
    {'play': 'Dh', 'deviation': null},
    {'play': 'Dh', 'deviation': null},
    {'play': 'Dh', 'deviation': null},
    {'play': 'Dh', 'deviation': null},
    {'play': 'Dh', 'deviation': null},
    {'play': 'Dh', 'deviation': null},
    {'play': 'Dh', 'deviation': null},
    {'play': 'Dh', 'deviation': null},
    {'play': 'H', 'deviation': '+2'},
  ],
  [
    {'heading': '10'},
    {'play': 'Dh', 'deviation': null},
    {'play': 'Dh', 'deviation': null},
    {'play': 'Dh', 'deviation': null},
    {'play': 'Dh', 'deviation': null},
    {'play': 'Dh', 'deviation': null},
    {'play': 'Dh', 'deviation': null},
    {'play': 'Dh', 'deviation': null},
    {'play': 'Dh', 'deviation': null},
    {'play': 'H', 'deviation': '+2'},
    {'play': 'H', 'deviation': '+2'},
  ],
  [
    {'heading': '9'},
    {'play': 'H', 'deviation': '+2'},
    {'play': 'Dh', 'deviation': null},
    {'play': 'Dh', 'deviation': null},
    {'play': 'Dh', 'deviation': null},
    {'play': 'Dh', 'deviation': null},
    {'play': 'H', 'deviation': '+2'},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
  ],
  [
    {'heading': '8'},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': '+2'},
    {'play': 'H', 'deviation': '+2'},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
  ],
  [
    {'heading': '<7'},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
  ],
  [
    {'heading': 'A8'},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': '+2'},
    {'play': 'H', 'deviation': '+2'},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
    {'play': 'H', 'deviation': null},
  ],
    [
    {'heading': ''}, 
    {'heading': '2'}, 
    {'heading': '3'}, 
    {'heading': '4'}, 
    {'heading': '5'}, 
    {'heading': '6'}, 
    {'heading': '7'}, 
    {'heading': '8'}, 
    {'heading': '9'}, 
    {'heading': '10'}, 
    {'heading': 'A'},
  ], // Dealer
];



  // {'dealer': '5', 'player': 'A8', 'answer': '+2'},
  // {'dealer': '6', 'player': 'A8', 'answer': '+2'},